[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
maplit = "1.0.2"
once_cell = "1.9.0"
phf = { version = "0.10", features = ["macros"] }